DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employees_db;

USE employees_db;

CREATE TABLE department (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(30) 
);

CREATE TABLE title (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(30),
    SALARY DECIMAL(10,0),
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES department(ID)
    ON DELETE CASCADE
);

CREATE TABLE employee (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    TITLE VARCHAR(30),
    TITLE_ID INT,
    DEPARTMENT VARCHAR(30),
    PAY DECIMAL(10,0),
    MANAGER_ID INT,
    FOREIGN KEY (TITLE_ID)
    REFERENCES TITLE(id)

    ON DELETE CASCADE
);