DROP DATABASE IF EXISTS employees_db;
CREATE DATABASE employees_db;

USE employees_db;

CREATE TABLE department (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE role (
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(30) NULL,
    SALARY DECIMAL(10,0) NULL,
    DEPARTMENT_ID INT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE employee (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NULL,
    LAST_NAME VARCHAR(30) NULL,
    ROLE_ID INT NULL,
    MANAGER_ID INT NULL,
    PRIMARY KEY (ID
    )
);